macro(follow_dependency lib_name)
    list(APPEND all_libraries ${lib_name})
    set(dependencies_name ${lib_name}_LIB_DEPENDS)
    if(DEFINED ${dependencies_name})
        set(dependencies ${${dependencies_name}})
        foreach(item ${dependencies})
            follow_dependency(${item})
        endforeach(item ${dependencies})
    endif(DEFINED ${dependencies_name})
endmacro(follow_dependency)

find_package(VTK REQUIRED)
message("CPPPATH=${VTK_INCLUDE_DIRS}")
message("LIBPATH=${VTK_LIBRARY_DIRS}")
# vtkHybrid is the catch-all VTK library
SET(all_libraries )
follow_dependency("vtkHybrid")
message("LIBS=${all_libraries}")
SET(all_libraries )
follow_dependency("vtkHybridPythonD")
message("PYTHON_LIBS=${all_libraries}")
message("vtk_wrap_python=${VTK_WRAP_PYTHON_EXE}")
message("vtk_wrap_python_init=${VTK_WRAP_PYTHON_INIT_EXE}")

