import itertools
from deployement.scons.itk import wrapitk_root
from deployement.scons.wrapitk import (Instantiation, 
                                       get_dimensions, get_scalar_types)

Import("env")
env = env.Clone()

env.Glob("*.py")

scalars = get_scalar_types(wrapitk_root())
dimensions = get_dimensions(wrapitk_root())

scalar_images = [Instantiation("itk::Image", *x) 
                 for x in itertools.product(scalars, dimensions)]
float_images = [Instantiation("itk::Image", "float", x) for x in dimensions]
images_3d = [Instantiation("itk::Image", x, 3) for x in scalars]

env.Use("vtk")

env.WrapITKPythonModule("MediPySegmentation", [
    ("itk::BETImageFilter", 
        [(x,x) for x in images_3d], "pointer"),
    ("itk::MonoModalStatisticalChangeDetectionImageFilter",
        [(x,x,x) for x in float_images], "pointer"),
    ("itk::ChangeDetectionClusteringImageFilter",
        [(x,x,x) for x in float_images], "pointer"),
    ("itk::ClustersToAnnotationsCalculator", 
        [(x,) for x in scalar_images], "pointer"),
])
