import os

targets = []

modules = ["annotations", "base", "control", "dicom", "function_gui_builder", 
           "image","io", "shapes", "xrc_wrapper"]
for module in modules :
    module_targets = SConscript(os.path.join(module, "SConstruct"))
    if module_targets :
        targets.extend(module_targets)
    else :
        print "No target defined for module {0}".format(module)

Import("env")
env = env.Clone()
targets.extend(env.Glob("*.py"))

Return("targets")
