Import("env")
env = env.Clone()

import itertools
from deployement.scons.wrapitk import get_instantiations

classes_template_info = []

# NumpyBridge
classes = ["itk::Image", "itk::VectorImage"]
types = ["float", "signed short", "signed long", "unsigned short", "unsigned long"]
dimensions = [2, 3]
instantiations = []
for class_ in classes :
    instantiations.extend(itertools.product(get_instantiations(class_, types, dimensions)))
classes_template_info.append(("itk::NumpyBridge", instantiations, None))

# MatrixBridge
types = ["float", "double"]
instantiations = []
for d in dimensions :
    instantiations.extend(itertools.product(get_instantiations("itk::Matrix", types, [d], [d])))
classes_template_info.append(("itk::MatrixBridge", instantiations, None))

env.WrapITKPythonModule("MediPyBridge", classes_template_info)

env.Glob("*.py")

