import itertools
from deployement.scons.itk import wrapitk_root
from deployement.scons.wrapitk import (Instantiation, 
                                       get_dimensions, get_scalar_types)

Import('env')
env = env.Clone()
env.Python(Glob("*.py"))

# Second Order Reconstruction Filter, instantiated for the following type (TInputImage and TOutputImage) :
# * itk::Image<float, 3>, itk::VectorImage<float, 3>    
types = get_scalar_types(wrapitk_root())
dimensions = get_dimensions(wrapitk_root())
instantiations = {
    "input" : [Instantiation("itk::Image", *x) 
               for x in itertools.product(types, dimensions)],
    "output" : [Instantiation("itk::VectorImage", *x) 
                for x in itertools.product(types, dimensions)]
}
instantiations = [(input, output) 
                  for input, output in zip(instantiations["input"], instantiations["output"])]

classes_template_info = [ ("itk::SecondOrderSymmetricTensorReconstructionFilter", instantiations, "pointer") ]
env.WrapITKPythonModule("SecondOrderSymmetricTensorReconstructionFilter", classes_template_info)

