import os
import sys
import deployement.scons.wrapitk

Import('env')
env = env.Clone()
env.Python(Glob("*.py"))

# Second Order Reconstruction Filter, instantiated for the following type (TInputImage and TOutputImage) :
# * itk::Image<float, 3>, itk::VectorImage<float, 3>    
types = ["float"]
dimensions = [3]
instantiations_input = deployement.scons.wrapitk.get_instantiations("itk::Image", types, dimensions)
instantiations_output = deployement.scons.wrapitk.get_instantiations("itk::VectorImage", types, dimensions)
instantiations = [(i,j) for i,j in zip(instantiations_input,instantiations_output)]
classes_template_info = [ ("itk::SecondOrderSymmetricTensorReconstructionFilter", instantiations, "pointer") ]
env.WrapITKPythonModule("SecondOrderSymmetricTensorReconstructionFilter", classes_template_info)

