# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_segmentation', [dirname(__file__)])
        except ImportError:
            import _segmentation
            return _segmentation
        if fp is not None:
            try:
                _mod = imp.load_module('_segmentation', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _segmentation = swig_import_helper()
    del swig_import_helper
else:
    import _segmentation
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def threshold(*args):
  return _segmentation.threshold(*args)
threshold = _segmentation.threshold
import medipy.base
from medipy.itk import itk_image_to_medipy_image, medipy_image_to_itk_image

unwrapped_threshold = threshold
def threshold(input,low,high,inside,outside,output) :
    """Binarize an input image by thresholding"""
    
    args = [input,low,high,inside,outside,output]
    itk_args = []
    
#Transform all arguments of type base.Image to itk.Image, keep the other
    for arg in args :
        if isinstance(arg, medipy.base.Image) :
            itk_image = medipy_image_to_itk_image(arg, False)
            itk_args.append(itk_image)
        else : 
        	itk_args.append(arg)
    
#Call the C/C++ threshold
    result = unwrapped_threshold(*itk_args)
    
#Transform back all arguments of type itk.Image to base.Image
    for i in range(len(args)) :
        if isinstance(args[i], medipy.base.Image) :
            itk_image_to_medipy_image(itk_args[i], args[i], True)
    
    return result



