#!/usr/bin/env python

##########################################################################
# MediPy - Copyright (C) Universite de Strasbourg, 2011-2012
# Distributed under the terms of the CeCILL-B license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
# for details.
##########################################################################

import medipy.base
import medipy.gui.base
import medipy.io

from main_frame import MainFrame

app = medipy.gui.base.Application()
app.SetAppName("MediPy/Viewer")

frame = MainFrame(None, size=(800,800))
frame.Show()

for url in app.arguments :
    try :
        image = medipy.io.load(url)
    except medipy.base.Exception, e :
        print e
    else :
        frame.ui.image.append_layer(image)

app.MainLoop()
