import os
import sys

sys.path.append(os.path.abspath(".."))
from deployement.scons import Environment

env = Environment(ENV = {"PATH" : os.environ["PATH"]})
env.Alias("install", "$PREFIX")
Export("env") 

plugins = [x.name for x in env.Glob("*") if x.name not in ["__init__.py", "SConstruct"]]
for plugin in plugins :
    SConscript(os.path.join(plugin, "SConstruct"))

env = env.Clone()
env.Glob("*.py")
