Import("env")
env = env.Clone()

targets = env.Glob("*.py")
if "install" in COMMAND_LINE_TARGETS :
    print "installing", [str(x) for x in targets]
#    env.Install("$PYTHON_PREFIX", targets)
Return("targets")