import os.path

Import('env')

env = env.Clone()
c_files = Glob("*.c")
cpp_files = Glob("*.cpp")

#env["CPPPATH"].append("../../")
env["CPPPATH"].append("../")
env["LIBPATH"].append("../")

output_files = env.SharedLibrary("medimax_wrapping", c_files + cpp_files, 
    LIBS = env["LIBS"]+["medimax"]+env["Python"]["LIBS"],
    CPPPATH=env["CPPPATH"]+env["Python"]["CPPPATH"], 
    LIBPATH=env["LIBPATH"]+env["Python"]["LIBPATH"])
#env.Install(env["lib_dir"], output_files)

env.Python(Glob("*.py"))