import itertools
from deployement.scons.wrapitk import (get_scalar_types, get_dimensions, 
                                       get_instantiations)
from deployement.scons.itk import wrapitk_root

Import("env")
env = env.Clone()

types = get_scalar_types(wrapitk_root())
dimensions = get_dimensions(wrapitk_root())

instantiations = get_instantiations("itk::Image", types, dimensions)
instantiations = [(i,i,i) for i in instantiations]
classes_template_info = [ ("itk::MaskWithValueImageFilter", instantiations, "pointer") ]
env.WrapITKPythonModule("MaskWithValueImageFilter", classes_template_info)

env.Glob("*.py")
