from traitement_interface import CorrectDarkBrightCoronalAlternation_gui
from traitement_interface import IntensityNormalisationForRegisteredImages_gui
from traitement_interface import ChamferDistance_GUI
