Import('env')

env = env.Clone()
env["LIBPATH"].append("../wrapping")
env["LIBPATH"].append("../")
env["CPPPATH"].append("../")

env.PythonModule("_traitement", ["traitement.i"], 
                 LIBS=["medimax_wrapping", "medimax"])

env.Python(Glob("*.py"))


