import os

modules = ["annotations", "base", "control", "dicom", "function_gui_builder", 
           "image","io", "shapes", "xrc_wrapper"]
for module in modules :
    SConscript(os.path.join(module, "SConstruct"))

Import("env")
env = env.Clone()
env.Glob("*.py")
