# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_scu', [dirname(__file__)])
        except ImportError:
            import _scu
            return _scu
        if fp is not None:
            try:
                _mod = imp.load_module('_scu', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _scu = swig_import_helper()
    del swig_import_helper
else:
    import _scu
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SCU(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SCU, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SCU, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _scu.new_SCU(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _scu.delete_SCU
    __del__ = lambda self : None;
    def GetConnection(self): return _scu.SCU_GetConnection(self)
    def SetConnection(self, *args): return _scu.SCU_SetConnection(self, *args)
    def __call__(self): return _scu.SCU___call__(self)
SCU_swigregister = _scu.SCU_swigregister
SCU_swigregister(SCU)

class SCUException(Exception):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SCUException, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SCUException, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _scu.new_SCUException(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _scu.delete_SCUException
    __del__ = lambda self : None;
    def what(self): return _scu.SCUException_what(self)
SCUException_swigregister = _scu.SCUException_swigregister
SCUException_swigregister(SCUException)

class Echo(SCU):
    __swig_setmethods__ = {}
    for _s in [SCU]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Echo, name, value)
    __swig_getmethods__ = {}
    for _s in [SCU]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Echo, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _scu.new_Echo(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _scu.delete_Echo
    __del__ = lambda self : None;
    def __call__(self): return _scu.Echo___call__(self)
Echo_swigregister = _scu.Echo_swigregister
Echo_swigregister(Echo)

class Find(SCU):
    __swig_setmethods__ = {}
    for _s in [SCU]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Find, name, value)
    __swig_getmethods__ = {}
    for _s in [SCU]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Find, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _scu.new_Find(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _scu.delete_Find
    __del__ = lambda self : None;
    def __call__(self): return _scu.Find___call__(self)
Find_swigregister = _scu.Find_swigregister
Find_swigregister(Find)

class Get(SCU):
    __swig_setmethods__ = {}
    for _s in [SCU]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Get, name, value)
    __swig_getmethods__ = {}
    for _s in [SCU]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Get, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _scu.new_Get(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _scu.delete_Get
    __del__ = lambda self : None;
    def __call__(self): return _scu.Get___call__(self)
Get_swigregister = _scu.Get_swigregister
Get_swigregister(Get)



