/*************************************************************************
 * MediPy - Copyright (C) Universite de Strasbourg, 2011
 * Distributed under the terms of the CeCILL-B license, as published by
 * the CEA-CNRS-INRIA. Refer to the LICENSE file or to
 * http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
 * for details.
 ************************************************************************/

/**-----------------------------------------------------------------------
***	
***	file:		imx_lang.h
***
***	project:	Imagix 1.01
***			
***
***	description:	Header file for project imagix (1.01)
***	
***	
***	Copyright (c) 1993, ULP-IPB Strasbourg.
***	All rights are reserved.
***
*** - This file specifies french or english text over all file
***
***
*** Updates:9
*** - When changing please issue your name... -
***	Last user action by: Mr. ARNOLD 		on November 20 1995
***     Last user action by: Mr. OURY		        on July 3rd 2000 
***
***---------------------------------------------------------------------*/

/*   Version Francaise du menu   */
#if LANG_FR==TRUE


#define TEXT0001	  "image"
#define TEXT0002          "Texte ?"
#define TEXT0003          "Taille du zoom ?"
#define TEXT0004          "Nombre ?"
#define TEXT0005          "Image a dilater:"
#define TEXT0006          "Image resultat:"
#define TEXT0007          "Nombre d'iterations:"
#define TEXT0008          "Carre 3*3"
#define TEXT0009          "H 3x3 Ver."
#define TEXT0010          "H 3x3 Hor."
#define TEXT0011          "Image a eroder:"
#define TEXT0012          "Image a amincir:"
#define TEXT0013          "Valeur du premier seuil:"
#define TEXT0014          "Valeur du deuxieme seuil:"
#define TEXT0015          "Image a filtrer:"
#define TEXT0016          "Valeur bas de la fenetre en %:"
#define TEXT0017          "Valeur haut de la fenetre en %:"
#define TEXT0018          "Image a labeliser:"
#define TEXT0019          "Nombre d'images a afficher : "
#define TEXT0020          "Choisissez le point de depart :\ndans la regurgitation de la premiere image a traiter"
#define TEXT0021          "Rotation de l'image:"
#define TEXT0022          "Image resultat moyenne:"
#define TEXT0023          "dans l'image:"
#define TEXT0024          "Pas ?"
#define TEXT0025          "Courbe"
#define TEXT0026          "Decalage de l'image:"
#define TEXT0027          "Zoom de l'image:"
#define TEXT0028          "Copie de l'image:"
#define TEXT0029          "Copie de l'image(forcee a 1)"
#define TEXT0030          "Recalage de l'image:"
#define TEXT0031          "Par rapport a l'image:"
#define TEXT0032          "Choix 1 point reference"
#define TEXT0033          "Choix 1 point"
#define TEXT0034          "Choix 2 point reference"
#define TEXT0035          "Choix 2 point"
#define TEXT0036          "Choix 3 point reference"
#define TEXT0037          "Choix 3 point"
#define TEXT0038          "Nom du fichier de la ROI:"
#define TEXT0039          "Cliquer sur l image"
#define TEXT0040          "Tracer la ROI"
#define TEXT0041          "De 1"
#define TEXT0042          "De 2"
#define TEXT0043          "Votre reponse:"
#define TEXT0044          "Image a seuiller:"
#define TEXT0045          "Miroir horizontal de l'image:"
#define TEXT0046          "Miroir vertical de l'image:"
#define TEXT0047          "Image fonctionnelle:"
#define TEXT0048          "a superposer sur image anatomique:"
#define TEXT0049          "Echange de l'image:"
#define TEXT0050          "avec l'image:"
#define TEXT0051          "Resultat de l'extraction:"
#define TEXT0052          "Numero pour sauvegarde de la ROI"
#define TEXT0053          "Valeur basse de seuillage:"
#define TEXT0054          "Image a remplir:"
#define TEXT0055          "Resultat segmentation:"
#define TEXT0056          "% de variation:"
#define TEXT0057          ""
#define TEXT0058          "Min de l'histo:"
#define TEXT0059          "Image a selectionner:"
#define TEXT0060          "Image resultat de la selection:"
#define TEXT0061          "Votre choix:"
#define TEXT0062          "Surface"
#define TEXT0063          "Position centre de gravite"
#define TEXT0064          "Valeur inf de la surface:"
#define TEXT0065          "Valeur sup de la surface:"
#define TEXT0066          "Image a analyser:"
#define TEXT0067          "Nombre de pas:"
#define TEXT0068          "Image binaire a analyser:"
#define TEXT0069          "----Pointez la cellule de l'image a examiner----"
#define TEXT0070          "Droite"
#define TEXT0071          "Gauche"
#define TEXT0072          "Bas"
#define TEXT0073          "Haut"
#define TEXT0074          "Fin"
#define TEXT0075          "Addition"
#define TEXT0076          "Soustraction"
#define TEXT0077          "Multiplication"
#define TEXT0078          "Division"
#define TEXT0079          "Absolu" 
#define TEXT0080          "Addition avec coeff"
#define TEXT0081          "Soustraction avec coeff"
#define TEXT0082          "Multiplication par coeff"
#define TEXT0083          "Division par coeff"
#define TEXT0084          "Trace manuel"
#define TEXT0085          "Cercle"
#define TEXT0086          "Ellipse"
#define TEXT0087          "Rectangle"
#define TEXT0088          "Carre"
#define TEXT0089          "Annulation trace"
#define TEXT0090          "Image resultat correlation:"
#define TEXT0091          "Image resultat fft:"
#define TEXT0092          "Visualisation courbe"
#define TEXT0093          "Nom du fichier resultat:"
#define TEXT0094          "Numero= "
#define TEXT0095          "Surface de la cellule= "
#define TEXT0096          "Centre de gravite ("
#define TEXT0097          "Nombre de points= _"
#define TEXT0098          "Moyenne= _"
#define TEXT0099          "Choix de la couleur (0,1,2,3,4,5,17,18)"
#define TEXT0100          "POINTEZ LA ZONE A ARCHIVER"
#define TEXT0101          "Choisissez le point de depart pour l'oeil gauche:"
#define TEXT0102          "Choisissez le point de depart pour l'oeil droit:"
#define TEXT0103          "     Choisissez la premiere image:     "
#define TEXT0104          "Choisissez la premiere image repos:"
#define TEXT0105          "Choisissez la premiere image activation:"
#define TEXT0106	  "Nom du fichier d'archive de la ROI "		
#define TEXT0107   	  "Entrer la nouvelle valeur de icomp"
#define TEXT0108          "Nouvelle valeur de dx "
#define TEXT0109          "Nouvelle valeur de dy "
#define TEXT0110          "Nouvelle valeur de dz "
#define TEXT0111          "Nombre de points"
#define TEXT0112          "Nombre d'images"
#define TEXT0113          "Nom fichier sur floppy"
#define TEXT0114          "Troncature fin de courbe en % / 1er point?"
#define TEXT0115          "Angle de rotation en degree"
#define TEXT0116          "La plus grande surface"
#define TEXT0117          "Par la valeur"
#define TEXT0118	  "Dimension N de la fenetre (NxN) "
#define TEXT0119	  "Intensite de l'objet ?"
#define TEXT0120	  "Premiere image a traiter : "
#define TEXT0121	  "Derniere image a traiter : "
#define TEXT0122	  "Nom du fichier A3000 a transferer : "
#define TEXT0123	  "Arriere"
#define TEXT0124	  "Avant"
#define TEXT0125	  "Dimension X"
#define TEXT0126	  "Dimension Y"
#define TEXT0127	  "Image de depart : module"
#define TEXT0128	  "Image de depart : phase"
#define TEXT0129	  "Image resultat : module"
#define TEXT0130	  "Image resultat : phase"
#define TEXT0131	  "Image de depart : partie reelle"
#define TEXT0132	  "Image de depart : partie imaginaire"
#define TEXT0133	  "Image resultat : partie reelle"
#define TEXT0134	  "Image resultat : partie imaginaire"
#define TEXT0135	  "Image de depart:"
#define TEXT0136	  "Decalage suivant X"
#define TEXT0137	  "Decalage suivant Y"
#define TEXT0138	  " Placez la ligne de coupe avec la souris \n    Deplacement de la ligne avec touche majuscule "
#define TEXT0139	  " Tracer le plan de coupe \n  Puis OK " 
#define TEXT0140	  " Choississez 3 points appartenant a la parabole\n Deplacement des pts  avec la touche majuscule"
#define TEXT0141	  " Choississez 3 points dont le sommet ( le 2e )\n Deplacement des pts avec la touche majuscule"
#define TEXT0142	  " Choississez 4 points de gauche a droite \n Deplacement des pts  avec la touche majuscule" 
#define TEXT0143	  " Placez les n points puis OK \n Deplacement des pts avec la touche majuscule" 
#define TEXT0144	  "Avec retour a la ligne"
#define TEXT0145	  "Sans retour a la ligne"
#define TEXT0146	  "Nb points a decaler"
#define TEXT0147	  "Temps de repetition (ms)"
#define TEXT0148	  "Image resultat amplitude"
#define TEXT0149	  "Image resultat T1"
#define TEXT0150	  "Image T1"
#define TEXT0151	  "Image T2 Mono"
#define TEXT0152	  "Image Amplitude"
#define TEXT0153	  "Temps entre echo (TE) (ms)"
#define TEXT0154	  "Image T2Long"
#define TEXT0155	  "Image T2Court"
#define TEXT0156	  "Image %AmpT2court"
#define TEXT0157	  "Seuil % pour traitement"
#define TEXT0158	  "Composante continue"
#define TEXT0159          "Cube 3*3*3"
#define TEXT0160          "Croix 3*3*3"
#define TEXT0161          "Position non valide"
#define TEXT0162          "Choississez le point de depart avec la souris"
#define TEXT0163          "Inversion"
#define TEXT0164          "Image de depart:"
#define	TEXT0165	  "Decalage suivant Z"
#define TEXT0166          "le fichier existe, ajouter ?"
#define TEXT0167          "Impossible de creer le fichier! Verifiez que le\n"
#define TEXT0168          "repertoire existe et que vous pouvez y ecrire.\n"
#define TEXT0169          "Ecraser l'ancien fichier ?"
#define TEXT0170	  "Choisissez le nombre d'image sur le film"
#define TEXT0171	  "Nombre de cines"
#define TEXT0172	  "Nombre d'images des cines"
#define TEXT0173	  "Choisissez le centre de l'animation"
#define TEXT0174	  "Translation suivant X ?"
#define TEXT0175	  "Translation suivant Y ?"
#define TEXT0176	  "Translation suivant Z ?"
#define TEXT0177	  "Zoom suivant X ?"
#define TEXT0178	  "Zoom suivant Y ?"
#define TEXT0179	  "Zoom suivant Z ?"
#define TEXT0180	  "Angle suivant X ?"
#define TEXT0181	  "Angle suivant Y ?"
#define TEXT0182	  "Angle suivant Z ?"
#define TEXT0183	  "image 1:"
#define TEXT0184	  "image 2 a soustraire:"
#define TEXT0185	  "Image de reference:"
#define TEXT0186  	  "Comparee a l'image:"
#define TEXT0187	  "taille de la fenetre N=3,5,7 "
#define TEXT0188	  "entrer une valeur pour le seuil de detection :10,20"
#define TEXT0189	  "erreur:N valeur entiere positive"
#define TEXT0190          "Choix de la table de couleurs"
#define TEXT0191	  "Plans 3*3*3"
#define TEXT0192	  "Valeur Positive"
#define TEXT0193	  "Valeur Negative"
#define TEXT0194	  "Valeur Negative et positive"
#define TEXT0195	  "Point hors de la grille"
#define TEXT0196	  "Manque de donnees"
#define TEXT0197	  "Moindres carres"
#define TEXT0198	  "Plus proche voisin"
#define TEXT0199	  "Interpolation trilineaire"
#define TEXT0200	  "Cliquez sur "
#define TEXT0201	  "Image non seuillee"
#define TEXT0202	  "Donnees incoherentes"
#define TEXT0203	  "la Commissure Anterieure  (AC)"
#define TEXT0204	  "la Commissure Posterieure  (PC)"
#define TEXT0205	  "le Point Anterieur  (AP)"
#define TEXT0206	  "le Point Posterieur  (PP)"
#define TEXT0207	  "le Point Droit  (RM)"
#define TEXT0208	  "le Point Gauche  (LM)"
#define TEXT0209	  "le Point Superieur  (SP)"
#define TEXT0210	  "le Point Inferieur  (IP)"
#define TEXT0211          "Choisissez un pixel"
#define TEXT0212          "Image en variable dependante (axe Y)"
#define TEXT0213          "Image resultat : nuage de points "
#define TEXT0214          "Valeur basse de la variable inependante en %"
#define TEXT0215          "Valeur haute de la variable inependante en % "
#define TEXT0216          "Erreur : valeur basse > valeur haute !"
#define TEXT0217          "Donnees pour regression lineaire"
#define TEXT0218          "Mode de remplissage de l'image resultat"
#define TEXT0219          "Ecart-type du bruit dans l'image"
#define TEXT0220          "Valeur strictement positive"
#define TEXT0221          "Probabilite des fausses alarmes"
#define TEXT0222          "Probabilite des fausses alarmes: nombre entre 0 et 1"
#define TEXT0223          "Hypothese sur la variance du signal"
#define TEXT0224	  "Image en variable independante (axe X)"
#define TEXT0225          "Objet opaque"
#define TEXT0226          "Objet transparent"
#define TEXT0227          "Difference d'images"
#define TEXT0228          "Valeur de la statistique"
#define TEXT0229          "Ecart des Moyennes"
#define TEXT0230          "Moyenne et ecart-type"
#define TEXT0231          "Image a normaliser"
#define TEXT0232          "En tenant compte de"
#define TEXT0233          "Regression lineaire a 2 parametres"
#define TEXT0234          "Rapport des moyennes"
#define TEXT1234          "Rapport Min/Max"
#define TEXT1235          "Regression lineaire a 1 parametre"
#define TEXT1236          "Regression lineaire TLS"
#define TEXT0235          "Ce test suppose une variance unitaire du bruit dans les deux images"
#define TEXT0236          "Seuil bas"
#define TEXT0237          "Seuil haut"
#define TEXT0238          "Croix X 3*3*3"
#define TEXT0239		  "Seuil d'agregation (0,255)"
#define TEXT0240          "Selectionner la ROI du ventricule gauche"
#define TEXT0241          "Selectionner la ROI myocardiaque"
#define TEXT0242          "Analyse compartimentale globale"
#define TEXT0300	  "Nombre de coupes ?"

#define TEXT0301          "Choisissez l'image a reduire"
#define TEXT0302          "Taux de reduction :"
#define TEXT0303          "Choisissez l'image a segmenter"
#define TEXT0304          "Image de segmentation"


/* Automates */

#define TEXT0348           "Longueur de %s (= %i) affectee a %s"
#define TEXT0349           "Erreur : Requiert une chaine de caract�eres"
#define TEXT0350           "Erreur : Type de variable incorrect"
#define TEXT0351           "Erreur : Requiert une variable numerique"
#define TEXT0352           "Erreur : Requiert des variables de meme type"
#define TEXT0353           "Erreur : Requiert un booleen"
#define TEXT0354           "Erreur : Impossible de changer de style. (%d)"
#define TEXT0355           "Style <%d> installe."
#define TEXT0356           "Nouveau chemin : %s."
#define TEXT0357           "Commande <<%s>> executee."
#define TEXT0358           "Erreur : nomenclature de variable inconnue (%s)."
#define TEXT0359           "Variable %s mise a %s."
#define TEXT0360           "Erreur : type de variable incorrect (%s)."
#define TEXT0361           "Variable %s incrementee a %s."
#define TEXT0362           "Expression <<%s>> evaluee a %s."
#define TEXT0363           "Erreur : Que fait la commande ELSE ici ?"
#define TEXT0364           "Bloc ELSE ignore."
#define TEXT0365           "Erreur : Que fait la commande ENDIF ici ?"
#define TEXT0366           "Fin du bloc IF."
#define TEXT0367           "Affichage de la chaine <<%s>>."
#define TEXT0368           "Debut de bloc FOR .. TO (%s de %f a %f)."
#define TEXT0369           "Erreur : nom de variable invalide pour le FOR."
#define TEXT0370           "Debut de bloc FOR .. IN (%s)."
#define TEXT0371           "Erreur : Que fait la commande NEXT ici ?"
#define TEXT0372           "Fin du bloc NEXT (%s)."
#define TEXT0373           "Fin de fichier atteint pour >%s<..."
#define TEXT0374           "Position courante : %ld"
#define TEXT0375           "Peut etre une valeur : %s"
#define TEXT0376           "Fin de fichier automatique. (%d ligne%c)."
#define TEXT0377           "Lecture de la commande suivante (%d) : >%s<"
#define TEXT0378           "Erreur : %s <tps> : <tps> doit etre > 0"
#define TEXT0379           "Erreur : %s <n> : <n> doit etre >= 0"
#define TEXT0380           "Fin de fichier atteint."
#define TEXT0381           "Desole, type inconnu...\nVoir imx_menu.h : " \
                          "_items[%d].menu_type"
#define TEXT0382           "Desole, commande inconnue...\nVoir imx_menu.h : " \
						  "_items[%d], ligne %d >%s< dans le fichier " \
						  "automatique"
#define TEXT0383           ">Fin du mode automatique"
#define TEXT0384           "Erreur : ouverture de fichier"
#define TEXT0385           "Erreur : trop de commandes 'end'"
#define TEXT0386           "Erreur : trop de commandes 'loop'"
#define TEXT0387           "Demarrage du mode automatique"
#define TEXT0388           "Erreur : ne peut pas sauvegarder les commandes" \
						  "         dans le fichier >%s<"
#define TEXT0389           "Effacer l'ancien fichier ?\n(%s)"
#define TEXT0390           "Erreur : Ouverture de fichier dans ATMLearn."
#define TEXT0391           "Envoi du message"
#define TEXT0392           "Erreur : definition de menu invalide"
#define TEXT0393           "Verifier le code"
#define TEXT0394           "Verifier la ligne %d ou le code %d dans le " \
						  "tableau de menu"
#define TEXT0395           "Comment est-il possible d'atteindre cette partie ???"
#define TEXT0396           "Desole, impossible de lire le fichier automatique !"
#define TEXT0397           "Nom du fichier automatique ?"
#define TEXT0398           "Impossible de traiter"
#define TEXT0399           "Fichier ?"
#define TEXT0400           "Impossible d'agir"
#define TEXT0401           "Fichier d'initialisation ?"
#define TEXT0402           "Fichier d'initialisation ? (avec car. generiques)"
#define TEXT0403           "Erreur dans la fonction " \
						  "donne_TclTk_char(buffer,position) \n" \
			              "verifiez les parametres buffer et position \n"
#define TEXT0404           "Erreur : chemin incorrect <<%s>>"
#define TEXT0405           ">Passage en mode manuel."
#define TEXT0406           ">Appel d'automate"
#define TEXT0407           "Mode pause"
#define TEXT0408           "Continuer"
#define TEXT0409           "Arreter"
#define TEXT0410           "Valeur pour l'argument $%d ?"
#define TEXT0411           "Variable non definie ($%s)"
#define TEXT0412           "Symboles %s non equilibres"

/* Coupes curvilignes & Atlas de Talairach*/

#define TEXT0413           "Extraire les donnees avant"
#define TEXT0414           "Pas de parameters dans cette image"
#define TEXT0415           "Image a activer"
#define TEXT0416           "De l'image"
#define TEXT0417           "A l'image"
#define TEXT0418           "Extraire les donnees de l'image"
#define TEXT0419           "Image a sauvegarder"
#define TEXT0420           "Fichier 3D ?"
#define TEXT0421           "Impossible d'enregistrer !"
#define TEXT0422           "Erreur lors de la sauvegarde au format IPB 3D"
#define TEXT0423           "Erreur lors de la lecture du header"
#define TEXT0424           "Erreur mise a jour TALA"
#define TEXT0425           "Action annulee"
#define TEXT0426           "Position dans le fichier (%d a %d) ?"
#define TEXT0427           "Impossible de lire le fichier %s."
#define TEXT0428           "Erreur mise a jour CURV"
#define TEXT0429           "Erreur lors de l'ecriture du header %s !"

/* Angiographie */

#define TEXT0450           "Projeter l'image"
#define TEXT0451           "Axe ?"
#define TEXT0452           "Angle ?"
#define TEXT0453           "Entree invalide ?"
#define TEXT0454           "Plus proche voisin"
#define TEXT0455           "Lineaire"
#define TEXT0456           "Quick cardinal 3"
#define TEXT0457           "Type de rotation ?"
#define TEXT0458           "Nombre de vues ?"

/* Gradients morphologiques */
#define TEXT0459           "gradient de base"
#define TEXT0460           "gradient interne"
#define TEXT0461           "gradient externe"
#define TEXT0462           "image a appliquer le gradient"

#define TEXT0463           "chapeau haut-de-forme blanc"
#define TEXT0464           "chapeau haut-de-forme noir"

#define TEXT0465           "image a appliquer l'ouverture"
#define TEXT0466           "image a appliquer la fermeture"
#define TEXT0467           "image a appliquer chapeau haut-de-forme"

/* Filtre butterworth */
#define TEXT0468           "ordre du filtre (1)"
#define TEXT0469           "frequence de coupure ((1/4)*largeur image)"
#define TEXT0470           "multiplicateur du filtre passbas (2)"
#define TEXT0471           "multiplicateur du filtre passhaut (0.5)"

/* Reconstruction geodesique par dilatation */
#define TEXT0472           "image originale (masque)"
#define TEXT0473           "image marqueur"

/* element structurant */
#define TEXT0474           "sphere 5x5"
#define TEXT0475           "demi-carre"
#define TEXT0476           "demi-croix +"
#define TEXT0477           "demi-plan"
#define TEXT0478           "demi-croix x"
#define TEXT0479           "demi-sphere"

#define TEXT0480           "coefficient d'adaptation (1)"
#define TEXT0481           "annuler"

#define TEXT0482           "image segmentee"

#define TEXT0500			"Impossible d'allouer l'objet grphic dans %s"
#define TEXT0510			"Impossible d'allouer l'objet grphic3d dans %s"

/* Boites de dialogue wxWindows */

/*           CIMXPictParameters */

#define TEXT0599			"Informations sur le patient"
#define	TEXT0600			"Nom du patient"
#define	TEXT0610			"Date de naissance"
#define	TEXT0620			"Praticien"
#define	TEXT0630			"Date de l'examen"
#define TEXT0635			"Resolution"
#define	TEXT0640			"dx"
#define	TEXT0650			"dy"
#define	TEXT0660			"dz"
#define	TEXT0665			"Dimensions"
#define	TEXT0670			"Largeur (X)"
#define	TEXT0680			"Hauteur (Y)"
#define	TEXT0690			"Profondeur (Z)"
#define TEXT0695			"Position"
#define	TEXT0700			"Pos X"
#define	TEXT0710			"Pos Y"
#define	TEXT0720			"Pos Z"
#define TEXT0725			"Plans de coupe"
#define	TEXT0730			"Plan de coupe X"
#define	TEXT0740			"Plan de coupe Y"
#define	TEXT0750			"Plan de coupe Z"
#define TEXT0755			"Zooms"
#define	TEXT0760			"Zoom"
#define	TEXT0770			"Zoom X"
#define	TEXT0780			"Zoom Y"
#define	TEXT0790			"Zoom Z"
#define TEXT0795			"Conversion"
#define	TEXT0800			"rcoef"
#define	TEXT0810			"icomp"
#define TEXT0815			"Valeurs des pixels"
#define	TEXT0820			"Pixel max"
#define	TEXT0830			"Pixel min"
#define	TEXT0831			"Seuil"
#define	TEXT0840			"Caracteristiques de l'image"

// selection de coupes auto-radiographiques					bertrand MARAT
	//question des menus
#define	TEXT0900			"Entrer le nom du fichier resultat (.ipb)"
#define	TEXT0901			"Entrer la taille de l'image en pixel (256)"
#define	TEXT0902			"Entrer a resolution de l'image en dpi (300)"
#define	TEXT0903			"Quelle position de visualisation des coupes (16)"
#define	TEXT0904			"Quelle position pour tester le seuillage ? (6)"
#define	TEXT0905			"Y a t il une gamme etalon ?"
#define	TEXT0906			"Entrer le nombre de valeur etalon (7) "
#define	TEXT0907			"Valeur du coefficient alpha (0)"
#define	TEXT0908			"Valeur du coefficient beta (1)"
#define	TEXT0909			"Ou se trouve la gamme etalon \0"


	// message d'erreur ou d'information
#define	TEXT0910			"Trop de bruit, trop petit pour etre selectionne"
#define	TEXT0911			"Extraction de coupe impossible : mauvais seuillage ou taille de fragment trop petit"
#define	TEXT0912			"Le point clique est invalide"
#define	TEXT0913			"Cliquer sur une coupe pour la selectionner"
#define	TEXT0914			"Seuillage impossible"
#define	TEXT0915			"Evaluation manuelle de la valeur de seuillage"
#define	TEXT0916			"Cliquer entre les coupes et la gamme etalon"
#define	TEXT0917			"Choisir parmis les gammes"
#define	TEXT0918			"Cliquer sur la gamme etalon pour entrer les valeurs correspondantes"
#define	TEXT0919			"Entrer la valeur d'etalonnage correspondant au fond "
#define	TEXT0920			"Valeur correspondant a la zone cliquee"
#define	TEXT0921			"Trop d'objet de taille superieure au fragment autorise"

	// choix des menus
#define	TEXT0930			"Manuelle"
#define	TEXT0931			"Semi_automatique"
#define	TEXT0932			"Automatique"
#define	TEXT0933			"Labellisation Auto/manu"
#define	TEXT0934			"Oui, une gamme etalon standard"
#define	TEXT0935			"Non, que des coupes "
#define	TEXT0936			"Je ne sais plus"
#define	TEXT0937			"En haut\0"
#define	TEXT0938			"En bas\0"
#define	TEXT0939			"Resolution de l'image PGM scannee (300) "

	//divers
#define	TEXT0950			"QUITTER ?"
#define	TEXT0951			"Autre fichier pgm ?"
#define	TEXT0952			"CHARGEMENT..."

/*-*/



#define	TEXT1000			"Quelle image ?"
#define TEXT1010			"Parcourir"
#define	TEXT1020			"Ouvrir un fichier"

#define TEXT1100			"Tous les fichiers (*)|*|" \
         					"Images 2D/3D MEDIMAX (*.ipb)|*.ipb|" \
							"Images 2D/3D Interfile (*.HDR)|*.HDR|" \
							"Automates (*.a)|*.a|" \
							"Champs de deformation (*.trf)|*.trf|" 
							

#define TEXT1200			"Caracteristiques generales"
#define TEXT1201			"Etats"
#define TEXT1202			"Appliquer"
#define TEXT1203			"Rafraichir"
#define TEXT1204			"Fichier"
#define TEXT1205			"Premiere image"
#define TEXT1206			"Increment"
#define TEXT1207			"Nombre d'images"
#define TEXT1208			"Nombre d'etats"
#define TEXT1209			"Erreur : nombre de parametres de l'automate " \
							"trop important"
#define TEXT1210			"Paravision"
#define TEXT1211			"Chg rep"
#define TEXT1212			"Repertoire"
#define TEXT1213			"Images / sequence"
#define TEXT1214			"Informations fMRI"
#define TEXT1215			"Image vide"

#define TEXT1300            "Erreur : detection du XVisual\n"
#define TEXT1310            "Erreur : ne peut creer %i couleurs " \
                            "(%i existantes pour %i maxi)\n"
#define TEXT1320            "Assertion: la table de couleurs %d n'existe " \
                            "pas (maximum %d)\n"
#define TEXT1330            "Quelle table de couleurs ?"
#define TEXT1340            "Nouvelle table de couleurs"
#define TEXT1350            "Assertion : position de l'image incorrecte " \
                            "(position %d, %d existantes)\n"
#define TEXT1360            "Quelle image ?"
#define TEXT1370            "Erreur : courbe de table de couleur %i inconnu\n"

#define TEXT1380            "Positif"
#define TEXT1390            "Negatif"
#define TEXT1400            "Symetrique"
#define TEXT1410            "Dissymetrique"
#define TEXT1420            "Mode d'affichage ?"
#define TEXT1430            "Erreur : toutes les tables sont affectees"
#define TEXT1440            "Erreur : evenement %s inexistant"
#define TEXT1450            "Automate incompatible. Utiliser le script " \
                            "'filtrer'"
#define TEXT1460            "Erreur : %s non positionne\n"
#define TEXT1470            "Position ?"

#define TEXT1480			"Images"
#define TEXT1490			"Tout selectionner"
#define TEXT1500			"Tout deselectionner"
#define TEXT1510			"Avec creation"
#define TEXT1520			"Remplacer"
#define TEXT1530			"Table remplacee"
#define TEXT1540			"Choix des valeurs"

#define TEXT1550			"Efface la boite de dialogue"
#define TEXT1560			"Erreur : ce n'est pas une table palier"
#define TEXT1570			"Couleur no"
#define TEXT1580			"Type : "
#define TEXT1590			"Valeurs reelles"
#define TEXT1600			"Pourcentage"
#define TEXT1610			"Inconnu"

#define TEXT1700            "OK"
#define TEXT1710            "Annuler"
#define TEXT1720            "Aide"
#define TEXT1730            "Fermer"
#define TEXT1740            "Oui"
#define TEXT1750            "Non"
#define TEXT1760            "Ajouter"
#define TEXT1770            "Supprimer"

#define TEXT1800            "IRMf"
#define TEXT1810            "Table des couleurs"
#define TEXT1820            "Choix d'un fichier"
#define TEXT1830            "Choix d'un fichier image"
#define TEXT1840            "Information"
#define TEXT1850            "Fichier existant"
#define TEXT1860            "Attention"
#define TEXT1870            "Resultat"
#define TEXT1880            "Erreur"
#define TEXT1890            "Erreur fatale"
#define TEXT1900            "A propos"

#define TEXT2000            "Fini ?"
#define TEXT2010            "Reglage du cutoff"
#define TEXT2020            "Cardio"

#define TEXT2100            "Superposer"

#define TEXT2200            "Execution d'automates"
#define TEXT2210            "Choix des stations"
#define TEXT2220            "Choix des automates"

#define TEXT2300            "Erreur: variable '%s' indefinie"

#define TEXT2400            "ROI"
#define TEXT2410            "Masque"
#define TEXT2420            "Choisissez l'image"
#define TEXT2430            "Choisissez le masque"

#define TEXT2500            "%s - Erreur : la palette de couleur no %d n'existe pas (%d)"

#define TEXT2600            "Fenetre 2D no %d\n"
#define TEXT2610            "%sType d'image : %s\n"
#define TEXT2620            "%sMasque : %s (%s)\n"
#define TEXT2630            "%sBits par pixel : %d\n"
#define TEXT2640            "%sAffichage : %s%s\n"
#define TEXT2650            "%sReferences : %d\n"
#define TEXT2660            "%sZoom : %d\n"
#define TEXT2670            "%sOffsets : x=%d y=%d\n"
#define TEXT2680            "%sCutoff : min=%d max=%d\n"
#define TEXT2690            "%sType : %c\n"
#define TEXT2700            "%sDimensions (pixels) : %dx%d\n"
#define TEXT2710            "%sValeurs de MRI : min=%d max=%d\n"
#define TEXT2720            "%sCoefficient de valeur reelle : rcoeff=%f icomp=%f\n"
#define TEXT2730            "%sResolution (mm) : dx=%f dy=%f dz=%f\n"
#define TEXT2740            "%sNom du fichier : %s (position %d)\n"
#define TEXT2750            "%sPatient : %s (%s)\n"
#define TEXT2760            "%sMedecin : %s\n"
#define TEXT2770            "%sDate d'examen : %s\n"
#define TEXT2780            "Fenetre 3D no %d\n"
#define TEXT2790            "%sDimensions (pixels) : %dx%dx%d\n"

#define TEXT2800            "Binaire"
#define TEXT2810            "Opaque"
#define TEXT2820            "Superpose"

#define TEXT2900            "Normal"

#define TEXT3000            "Active"
#define TEXT3010            "Desactive"
#define TEXT3020            "Palette"
#define TEXT3030            "Valeurs"
#define TEXT3040            "-"

#define TEXT3100            "%sPalette de couleurs : %s (no %d, identifiant %d)\n"
#define TEXT3110            "%sMode d'affichage : %s\n"
#define TEXT3120            "%sType de palette : %s\n"

#define TEXT3200            "Valeur reelle"
#define TEXT3210            "Pourcentage"
#define TEXT3220            "Dynamique"
#define TEXT3230            "Palier"
#define TEXT3240            "Indefini"

/* messages vascular segmentation */

#define TEXT6000            "Image de module"
#define TEXT6001            "Image de phase"
#define TEXT6002            "Image resultat"
#define TEXT6003            "Seuil de segmentation de la tete"
#define TEXT6004            "Dimension de l'element structurant"
#define TEXT6005            "Seuil haut"
#define TEXT6006            "Seuil bas"
#define TEXT6007            "Coupe"
#define TEXT6008            "Image a dilater"
#define TEXT6009            "Taille ES"
#define TEXT6010            "Image initiale"
#define TEXT6011            "Image atlas"
#define TEXT6012            "Image atlas haut"
#define TEXT6013            "Image atlas bas"




/* messages Markov segmentation */
#define MASK_QUEST          "Choix"
#define FULL_IMAGE          "Toute l'image"
#define WITHOUT_BG          "Image seuillee"
#define NBR_CLASS_QUEST     "Nombre de  classes ?"
#define ERR_NBITER          "Erreur: Nombre d'iterations <=0\n"
#define ERR_NBCLASSES       "Erreur: Nombre de classes <=0\n"
#define ALGORITHM           "Algorithme d'estimation ?"
#define QUEST_EM            "EM (rapidite)"
#define QUEST_ICE           "ICE (qualite)"
#define QUEST_SEM           "SEM"
#define INIT_MARKOV         "Initialisation ?"
#define TEXT_NO_INIT        "Aucune"
#define TEXT_KMEAN          "K-moyennes"
#define TEXT_FUZZY_KMEAN    "K-moyennes floue"
#define ERR_MASK            "Erreur: l'image ne contient pas de masque\n"
#define MULTI_1             "Permiere modalite"
#define MULTI_2             "Deuxieme modalite"
#define MULTI_3             "Troisieme modalite"
#define YES_DECORR          "OUI"
#define NO_DECORR           "NON"
#define DECORR              "Decorrelation des observations ?"
#define REDUC               "Le dernier axe de projection represente\n moins de 10% de l'energie\nReduction de l'espace des observations?"
#define SURSEG              "Souhaitez-vous resegmenter l'un des labels obtenus?"
#define SURSEG_RESUL        "Resultats sursegmentation"
#define SUBADD              "Que souhaitez vous faire"
#define KEEP_ONE            "Conserver un seul label"
#define DEL_ONE             "Supprimer un label"


/* messages fMRI */
#define ERR_MEM_ALLOC		"Erreur d'allocation memoire"
#define ERR_LOAD_MRI		"Erreur : impossible de charger le fichier mri"
#define ERR_SAVE_PARAD		"Erreur : impossible d'enregistrer le paradigme"
#define ERR_NO_PARAD		"Erreur : il n'y a pas de paradigme a enregistrer\n"
#define ERR_NOT_A_PARAD		"Erreur : ce fichier n'est pas un paradigme\n"
#define ERR_NOT_2D_PARAD	"Erreur : ce fichier n'est pas un paradigme 2D\n"
#define ERR_NOT_3D_PARAD	"Erreur : ce fichier n'est pas un paradigme 3D\n"
#define ERR_PARAD_VOID		"Erreur : aucun paradigme n'a ete cree\n"
#define ERR_CANT_MAKE_PAR	"Erreur : impossible de creer le paradigme\n"
#define ERR_CANT_SAVE		"Erreur : impossible d'enregistrer dans ce repertoire\n"
#define ERR_IMG_NOT_LOADED	"Erreur : les images n'ont pas ete chargees\n"
#define ERR_N_STATUS		"Erreur : Au moins 2 etats en IRMf\n"
#define ERR_NO_RUPTURES         "Erreur : les ruptures n'ont pas ete chargees\n"

#define WRN_NIMG_SUP_PARAD	"Attention : le nombre d'images est superieur au nombre d'etats du paradigme.\n"
#define WRN_PARAD_SUP_NIMG	"Attention : le nombre d'etats du paradigme est superieur au nombre d'images.\n"

#define MSG_IGN_PATHS		"Ignorer les chemins des images"
#define MSG_SAVE_PATHS		"Inclure les chemins des images"
#define MSG_CHOICE			"Selectionnez votre choix"

#define TXT_PARAD_VISU		"Visualisation du paradigme"
#define TXT_REST			"REPOS"
#define TXT_ACTIV			"ETAT "
#define TXT_STAT1			"ETAT 1"
#define TXT_STAT2			"ETAT 2"
#define TXT_STAT_ALL		"Tous les etats"
#define TXT_IMG_MAP             "image de la carte"
#define TXT_IMG_DELAY           "image des retards"

#define ASK_N_STATUS		"Entrez le nombre d'etats :"
#define ASK_THRES_PROC		"Entrez le seuil de traitement. (Valeur actuelle : %f)"

/* fin fMRI */
#define	UNIX_CMD_QUEST      "Entrez votre commande ?"
#define	CHDIR_CMD_QUEST 	"Quel repertoire ?"
#define	PLACE_MESG          "A quel endroit ?"
#define	OKCANCEL_MESG   "Validation"
#define	ANYVALUE_MESG   "Entrez une valeur"

#define ABOUT_MESG	"\nMedimax 2.01      \
             \n Copyright (c) 1993-2000 ULP-IPB-LSIIT Strasbourg\n   \
\n  J.P. Armspach \
\n  Ph. Etter, C. Nikou, 0. Musse, F. Bouleau  \
\n  T. BERST\
\n  and all students..... \n  \
\n All rights reserved GITIM\
\n http://www-ipb.u-strasbg.fr/gitim"  


#endif

#define TEXT9000	  "Quel type d'element structurant ?"
#define TEXT9001	  "Zones plates uniquement"
#define TEXT9002          "Reconstruction geodesique"
#define TEXT9003          "Ligne de partage des eaux"
#define TEXT9004          "Temporel"
#define TEXT9005          "Croix 4D"
#define TEXT9006          "Croix-Croix-Croix (20-c)"
#define TEXT9007          "Point-Boule-Point (28-c)"
#define TEXT9008          "Croix-Boule-Croix (40-c)"
#define TEXT9009          "Boule 4D (80-c)"


/*    Version Anglaise du menu   */
#if LANG_US==TRUE



#define TEXT0001	  "image"
#define TEXT0002          "Text ?"
#define TEXT0003          "Zoom size ?"
#define TEXT0004          "Number ?"
#define TEXT0005          "Image to dilate:"
#define TEXT0006          "Result image:"
#define TEXT0007          "Nombre d'iteration:"
#define TEXT0008          "Square 3*3"
#define TEXT0009          "H 3*3 Ver."
#define TEXT0010          "H 3*3 Hor."
#define TEXT0011          "Image to erode:"
#define TEXT0012          "Image to thin down:"
#define TEXT0013          "Value of first threshold:"
#define TEXT0014          "Value of second threshold:"
#define TEXT0015          "Image to filter:"
#define TEXT0016          "Low value of the windows (%):"
#define TEXT0017          "High value of the windows (%):"
#define TEXT0018          "Image to label:"
#define TEXT0019          "Number of images to display : "
#define TEXT0020          "Choose starting point :\ninto the regurgitation of the first image to treat"
#define TEXT0021          "Image to rotate:"
#define TEXT0022          "Mean result image:"
#define TEXT0023          "into image:"
#define TEXT0024          "Step ?"
#define TEXT0025          "Curve"
#define TEXT0026          "Shift of image :"
#define TEXT0027          "Image zoom "
#define TEXT0028          "Copy of image:"
#define TEXT0029          "Copy of image (forced at 1)"
#define TEXT0030          "Registration of Image :"
#define TEXT0031          "Regard to image:"
#define TEXT0032          "Choose reference point 1"
#define TEXT0033          "Choose point 1"
#define TEXT0034          "Choose reference point 2"
#define TEXT0035          "Choose point 2"
#define TEXT0036          "Choose reference point 3"
#define TEXT0037          "Choose point 3"
#define TEXT0038          "File name of ROI:"
#define TEXT0039          "Click on the image"
#define TEXT0040          "Trace ROI"
#define TEXT0041          "De 1" /* perdu */
#define TEXT0042          "De 2" /* perdu */
#define TEXT0043          "Your answer:"
#define TEXT0044          "Image to threshold:"
#define TEXT0045          "Horizontal  mirror of image:"
#define TEXT0046          "Vertical mirror of image:"
#define TEXT0047          "functional image :"
#define TEXT0048          "to superpose on anatomical image :"
#define TEXT0049          "Exchange of image:"
#define TEXT0050          "With image:"
#define TEXT0051          "Result of extraction:"
#define TEXT0052          "Number for save image"
#define TEXT0053          "Low value of threshold:"
#define TEXT0054          "Image to fill:"
#define TEXT0055          "Result of segmentation:"
#define TEXT0056          "% of variation:"
#define TEXT0057          ""
#define TEXT0058          "Min of histo:"
#define TEXT0059          "Image to select:"
#define TEXT0060          "Result image of selection:"
#define TEXT0061          "Your choice:"
#define TEXT0062          "Area"
#define TEXT0063          "Position of centre of gravity"
#define TEXT0064          "Low value of area:"
#define TEXT0065          "High value of area:"
#define TEXT0066          "Image to analyse:"
#define TEXT0067          "Nunber of step:"
#define TEXT0068          "Binary image to analyse:"
#define TEXT0069          "----Point the cell of the image to analyse----"
#define TEXT0070          "Right"
#define TEXT0071          "Left"
#define TEXT0072          "Down"
#define TEXT0073          "Up"
#define TEXT0074          "End"
#define TEXT0075          "Addition"
#define TEXT0076          "Substraction"
#define TEXT0077          "Multiplication" 
#define TEXT0078          "Division"
#define TEXT0079          "Absolute"
#define TEXT0080          "Addition with coef"
#define TEXT0081          "Substraction with coef"
#define TEXT0082          "Multiplication with coef"
#define TEXT0083          "Division with coef"
#define TEXT0084          "Manual trace"
#define TEXT0085          "Circle"
#define TEXT0086          "Ellipse"
#define TEXT0087          "Rectangle"
#define TEXT0088          "Square"
#define TEXT0089          "Cancel trace"
#define TEXT0090          "Correlation result image:"
#define TEXT0091          "fft result image:"
#define TEXT0092          "Show curve"
#define TEXT0093          "Result file name:"
#define TEXT0094          "Number= "
#define TEXT0095          "Cell area= "
#define TEXT0096          "Center of gravity ( "
#define TEXT0097          "Number of points= _"
#define TEXT0098          "Mean= _"
#define TEXT0099          "Choice of colors (0,1,2,3,4,5,17,18)"
#define TEXT0100          "CHOOSE THE ARCHIVE ZONE"
#define TEXT0101          "Choose the starting point for the left eye:"
#define TEXT0102          "Choose the starting point for the right eye:"
#define TEXT0103          "Choose the first image:"
#define TEXT0104          "Choose the first image repos:"
#define TEXT0105          "Choose the first image activation:"
#define TEXT0106          "Name of ROI file "
#define TEXT0107          "Enter the new value of icomp"
#define TEXT0108          "New value of dx "
#define TEXT0109          "New value of dy "
#define TEXT0110          "New value of dz "
#define TEXT0111          "Number of points"
#define TEXT0112          "Number of images"
#define TEXT0113          "Name file on floppy"
#define TEXT0114          "Troncate end of data in % / first point?"
#define TEXT0115          "Rotation angle in degree"
#define TEXT0116          "The greatest area"
#define TEXT0117          "The value"
#define TEXT0118 	  "Dimension N of the window (NxN) "
#define TEXT0119	  "Object intensity ?"
#define TEXT0120	  "First image to treat"
#define TEXT0121	  "Last image to treat"
#define TEXT0122	  "A3000 File name to transfer : "
#define TEXT0123	  "Rear"
#define TEXT0124	  "Front"
#define TEXT0125	  "Dimension X"
#define TEXT0126	  "Dimension Y"
#define TEXT0127	  "Starting image : module"
#define TEXT0128	  "Starting image : phase"
#define TEXT0129	  "Result image : module"
#define TEXT0130	  "Result image : phase"
#define TEXT0131	  "Starting image : real component"
#define TEXT0132 	  "Starting image : imaginary component"
#define TEXT0133	  "Result image : real component"
#define TEXT0134	  "Result image : imaginary component"
#define TEXT0135	  "Start image :"
#define TEXT0136	  "X Shift"
#define TEXT0137	  "Y Shift"
#define TEXT0138	  " Put the line with the mouse \n    Moving the line with the Shift key"
#define TEXT0139	  " Trace and then 'OK' " 
#define TEXT0140	  " Take 3 points of the parable \n Moving the points with the Shift key"
#define TEXT0141	  " Take 2 points of the parable and its top \n Moving the points with the Shift key"
#define TEXT0142	  " Take 4 points from left to right \n Moving the points with the Shift key"
#define TEXT0143	  " Placez les n points puis OK \n Deplacement des pts avec la touche majuscule" 
#define TEXT0144	  "With cariage return"
#define TEXT0145	  "Without cariage return"
#define TEXT0146	  "Nb of points to shift"
#define TEXT0147	  "Repetition time (ms)"
#define TEXT0148	  "Resulting amplitude image"
#define TEXT0149	  "Resulting T1 image"
#define TEXT0150	  "T1 Image"
#define TEXT0151	  "T2 Mono Image"
#define TEXT0152	  "Amplitude image"
#define TEXT0153	  "Echo timeo (TE) (ms)"
#define TEXT0154	  "T2Long Image"
#define TEXT0155	  "T2Short Image"
#define TEXT0156	  "%AmpT2short Image"
#define TEXT0157	  "Threshold % for treatment"
#define TEXT0158	  "Offset"
#define TEXT0159          "Cube 3*3*3"
#define TEXT0160          "Cross 3*3*3"
#define TEXT0161          "Not valid position"
#define TEXT0162          "Choose the start point with the mouse"
#define TEXT0163          "Inversion"
#define TEXT0164          "Image to treat:"
#define TEXT0165	  "Z Shift"
#define TEXT0166          "File exist, append ?"
#define TEXT0167          "Cannot create file! Directory must exist and you\n"
#define TEXT0168          "must have write permission.\n"
#define TEXT0169          "Erase old file ?"
#define TEXT0170	  "choose the number of images on the film"
#define TEXT0171	  "Number of movies"
#define TEXT0172	  "Number of movie images" 
#define TEXT0173	  "Click on the center of the animation" 
#define TEXT0174	  "Translation  X ?"
#define TEXT0175	  "Translation  Y ?"
#define TEXT0176	  "Translation  Z ?"
#define TEXT0177	  "Zoom  X ?"
#define TEXT0178	  "Zoom  Y ?"
#define TEXT0179	  "Zoom  Z ?"
#define TEXT0180	  "Angle X ?"
#define TEXT0181	  "Angle Y ?"
#define TEXT0182	  "Angle Z ?"
#define TEXT0183	  "image 1:"
#define TEXT0184	  "image 2 to subtract:"
#define TEXT0185	  "Reference image:"
#define TEXT0186  	  "To compare with the image"
#define TEXT0187	  "size of the window N=3,5,7 "
#define TEXT0188	  "give a number for the detection threshold:10,20"
#define TEXT0189	  "error:N must be a POSITIF integer"
#define TEXT0190          "Choice of the colors table"
#define TEXT0191	  "Plans 3*3*3"
#define TEXT0192	  "Positive value"
#define TEXT0193	  "Negative value"
#define TEXT0194	  "Negative and positive value"
#define TEXT0195	  "Out of the grid"
#define TEXT0196	  "No data"
#define TEXT0197	  "Least squares"
#define TEXT0198	  "Nearest neighbour"
#define TEXT0199	  "Trilinear interpolation"
#define TEXT0200	  "Click on "
#define TEXT0201	  "Not a threshold image"
#define TEXT0202	  "Inconsistents datas"
#define TEXT0203	  "Anterior Commissure  (AC)"
#define TEXT0204	  "Posterior Commissure  (PC)"
#define TEXT0205	  "Anterior Point  (AP)"
#define TEXT0206	  "Posterior Point  (PP)"
#define TEXT0207	  "Right Medial  (RM)"
#define TEXT0208	  "Left Medial  (LM)"
#define TEXT0209	  "Superior Point  (SP)"
#define TEXT0210	  "Inferior Point  (IP)"
#define TEXT0211          "Choose a pixel"

#define TEXT0212          "Image as dependent variable (Y axis)"
#define TEXT0213          "Image of resulting point cloud" 
#define TEXT0214          "independent variable lower bound (in %)"
#define TEXT0215          "independent variable upper bound (in %)"
#define TEXT0216          "lower value > upper value !"
#define TEXT0217          "Data for linear regression"
#define TEXT0218          "Result image filled with :"
#define TEXT0219          "Noise standard deviation in image"
#define TEXT0220          "Enter a positive number"
#define TEXT0221          "Probability of false alarm" 
#define TEXT0222          "Probability of false alarm : number in between 0-100"
#define TEXT0223          "Hypothesis on signal variance"
#define TEXT0224          "Image as independent variable (X axis)"
#define TEXT0225          "Opaque object"
#define TEXT0226          "Transparent object"
#define TEXT0227          "Difference of Images"
#define TEXT0228          "Statistic Test Value"
#define TEXT0229          "Mean difference"
#define TEXT0230          "Mean and standard deviation"
#define TEXT0231          "Normalize Image"
#define TEXT0232          "With"
#define TEXT0233          "Linear regression, 2 parameters"
#define TEXT0234          "mean ration"
#define TEXT1234          "Min/Max"
#define TEXT1235          "Linear regression, 1 parameter"
#define TEXT1236          "Total Least Squares Linear regression"
#define TEXT0235          "This test needs images with unit noise variance"
#define TEXT0236          "Low threshold"
#define TEXT0237          "High threshold"
#define TEXT0238          "Cross X 3*3*3"
#define TEXT0239		  "Agregation threshold (0,255)"
#define TEXT0240          "Select left Ventricul ROI"
#define TEXT0241          "Select myocardical ROI"
#define TEXT0242          "Global Compartimental Analysis"
#define TEXT0300	  "Number of slices ?"

#define TEXT0301          "Choose the reduced image"
#define TEXT0302          "Choose reduction rate"
#define TEXT0303          "Choose the image to segment"
#define TEXT0304          "Segmentation image"

/* Automates */

#define TEXT0348           "Length of  %s (= %i) set in %s"
#define TEXT0349           "Error : string variable required"
#define TEXT0350           "Error : variable's type mismatch"
#define TEXT0351           "Error : numeric variable required"
#define TEXT0352           "Error : variables of same type required"
#define TEXT0353           "Error : boolean required"
#define TEXT0354           "Error : cannot change style. (%d)"
#define TEXT0355           "Style <%d> installed."
#define TEXT0356           "New path : %s."
#define TEXT0357           "Command <<%s>> executed."
#define TEXT0358           "Error : unknown variable's nomenclature (%s)."
#define TEXT0359           "Variable %s set to %s."
#define TEXT0360           "Error : variable's type mismatch (%s)."
#define TEXT0361           "Variable %s set to %s."
#define TEXT0362           "Expression <<%s>> evaluated to %s."
#define TEXT0363           "Error : what does ELSE command do here ?"
#define TEXT0364           "Block ELSE ignored."
#define TEXT0365           "Error : what does ENDIF command do here ?"
#define TEXT0366           "End of IF block."
#define TEXT0367           "Echoing string <<%s>>."
#define TEXT0368           "Starting FOR .. TO block (%s from %f to %f)."
#define TEXT0369           "Error : variable's name mismatch for FOR command."
#define TEXT0370           "Starting FOR .. IN block (%s)."
#define TEXT0371           "Error : what does NEXT command do here ?"
#define TEXT0372           "End of NEXT block (%s)."
#define TEXT0373           "End of file reaches for >%s<..."
#define TEXT0374           "Current position : %ld"
#define TEXT0375           "Can be a value : %s"
#define TEXT0376           "End of automatic file. (%d line%c)."
#define TEXT0377           "Next line read (%d) : >%s<"
#define TEXT0378           "Error : %s <time> : <time> must be > 0"
#define TEXT0379           "Error : %s <n> : <n> must be >= 0"
#define TEXT0380           "End of file reached."
#define TEXT0381           "Sorry, unknown type...\nSee imx_menu.h : " \
                          "_items[%d].menu_type"
#define TEXT0382           "Sorry, unknown command...\nSee imx_menu.h : " \
						  "_items[%d], line %d >%s< in automatic file"
#define TEXT0383           ">End of automatic mode"
#define TEXT0384           "Error : opening file"
#define TEXT0385           "Error : too much 'end' commands"
#define TEXT0386           "Error : too much 'loop' commands"
#define TEXT0387           "Starting automatic mode"
#define TEXT0388           "Error : cannot save commands in file >%s<"
#define TEXT0389           "Erase old file ?\n(%s)"
#define TEXT0390           "Error : opening file in ATMLearn."
#define TEXT0391           "Sending message"
#define TEXT0392           "Error : invalid menu definition"
#define TEXT0393           "Check code"
#define TEXT0394           "Check line %d or code %d in menu array"
#define TEXT0395           "How is it possible to reach this part ???"
#define TEXT0396           "Sorry, cannot read automatic file !"
#define TEXT0397           "Automatic file's name ?"
#define TEXT0398           "Cannot learn"
#define TEXT0399           "Fichier ?"
#define TEXT0400           "Cannot act"
#define TEXT0401           "Init file ?"
#define TEXT0402           "Init file ? (with wildcards)"
#define TEXT0403           "Error in donne_TclTk_char(buffer,position)" \
			              "function\nCheck buffer and position params\n"
#define TEXT0404           "Error : incorrect path <<%s>>"
#define TEXT0405           ">Coming back to handy mode."
#define TEXT0406           ">Automate call"
#define TEXT0407           "Pause mode"
#define TEXT0408           "Continue"
#define TEXT0409           "Stop"
#define TEXT0410           "Value for argument $%d ?"
#define TEXT0411           "Undefined variable ($%s)"
#define TEXT0412           "%s symbols mismatching"

/* Curvilinear & Talairach*/

#define TEXT0413           "Extract data before"
#define TEXT0414           "No parameters in this image"
#define TEXT0415           "Image to activate"
#define TEXT0416           "From image"
#define TEXT0417           "To image"
#define TEXT0418           "Image where data are to be extracted"
#define TEXT0419           "Image to save"
#define TEXT0420           "3D File ?"
#define TEXT0421           "Sorry, cannot save!"
#define TEXT0422           "Error saving IPB 3D format"
#define TEXT0423           "Error reading header file"
#define TEXT0424           "Error updating TALA"
#define TEXT0425           "Action cancelled"
#define TEXT0426           "Image position in file?"
#define TEXT0427           "Cannot read file %s."
#define TEXT0428           "Error updating CURV"
#define TEXT0429           "Error writing header %s!"

/* Angiography */

#define TEXT0450           "Project image"
#define TEXT0451           "Axis ?"
#define TEXT0452           "Angle ?"
#define TEXT0453           "Invalid entry"
#define TEXT0454           "Nearest neighbour"
#define TEXT0455           "Linear"
#define TEXT0456           "Quick cardinal 3"
#define TEXT0457           "Kind of rotation ?"
#define TEXT0458           "Number of views ?"

/* Morphological gradient */
#define TEXT0459           "Beucher gradient"
#define TEXT0460           "internal gradient"
#define TEXT0461           "external gradient"
#define TEXT0462           "image to apply gradient"

#define TEXT0463           "white top-hat"
#define TEXT0464           "black top-hat"

#define TEXT0465           "image to apply opening"
#define TEXT0466           "image to apply closing"
#define TEXT0467           "image to apply top-hat"

/* butterworth filter*/
#define TEXT0468           "butterworth order (1)"
#define TEXT0469           "cutoff frequency ((1/4)*image width)"
#define TEXT0470           "lowpass multiplicator (2)"
#define TEXT0471           "highpass multiplicator (0.5)"

/* geodesic reconstruction by dilation */
#define TEXT0472           "initial image (mask)"
#define TEXT0473           "marker image"

/* strcuturing element */
#define TEXT0474           "sphere 5x5"
#define TEXT0475           "half square"
#define TEXT0476           "half cross +"
#define TEXT0477           "half plane"
#define TEXT0478           "hafl cross x"
#define TEXT0479           "half sphere"

#define TEXT0480           "coefficient of adaptation"
#define TEXT0481           "cancel"

#define TEXT0482           "Segmented image"

#define TEXT0500			"Can't allocate a grphic object in %s"
#define TEXT0510			"Can't allocate a grphic3d object in %s"

/* wxWindows dialog boxes       */

/*           CIMXPictParameters */

#define TEXT0599			"Patient's informations"
#define	TEXT0600			"Patient's name"
#define	TEXT0610			"Birthdate"
#define	TEXT0620			"Practicien"
#define	TEXT0630			"Exam's date"
#define TEXT0635			"Resolution"
#define	TEXT0640			"dx"
#define	TEXT0650			"dy"
#define	TEXT0660			"dz"
#define	TEXT0665			"Sizes"
#define	TEXT0670			"Width (X)"
#define	TEXT0680			"Height (Y)"
#define	TEXT0690			"Depth (Z)"
#define TEXT0695			"Location"
#define	TEXT0700			"Pos X"
#define	TEXT0710			"Pos Y"
#define	TEXT0720			"Pos Z"
#define TEXT0725			"Cut planes"
#define	TEXT0730			"Cut plane X"
#define	TEXT0740			"Cut plane Y"
#define	TEXT0750			"Cut plane Z"
#define TEXT0755			"Zooms"
#define	TEXT0760			"Zoom"
#define	TEXT0770			"Zoom X"
#define	TEXT0780			"Zoom Y"
#define	TEXT0790			"Zoom Z"
#define TEXT0795			"Conversion"
#define	TEXT0800			"rcoef"
#define	TEXT0810			"icomp"
#define TEXT0815			"Pixels' values"
#define	TEXT0820			"Max pixel"
#define	TEXT0830			"Min pixel"
#define	TEXT0831			"Get threshold"

#define	TEXT0840			"Picture's characteristics"

// selection de coupes auto-radiographiques					bertrand
	//question des menus
#define	TEXT0900			"Enter name for file result (.ipb)"
#define	TEXT0901			"Enter picture size (fragment) in pixel(256)"
#define	TEXT0902			"Enter picture resolution in dpi (300)"
#define	TEXT0903			"Which position to show selected auto-radiographic pictures (16)"
#define	TEXT0904			"Which position to test thresholding ? (6)"
#define	TEXT0905			"Is there a Standard ?"
#define	TEXT0906			"Give the number of standard values (7) "
#define	TEXT0907			"Value for alpha coefficent (0)"
#define	TEXT0908			"Value for beta coefficent (1)"
#define	TEXT0909			"Where is the standard ?"


	// message d'erreur ou d'information
#define	TEXT0910			"Too much noise, too small to be selected"
#define	TEXT0911			"Unable yo extract : bad threshold or size fragment too small"
#define	TEXT0912			"Mouse clic point not OK"
#define	TEXT0913			"Clic in pictures to select them"
#define	TEXT0914			"Unable to threshold"
#define	TEXT0915			"Handing threshold"
#define	TEXT0916			"Click beetwin pictures and standard"
#define	TEXT0917			"Choose beetwin these standard"
#define	TEXT0918			"Clic in the standard area to give the value"
#define	TEXT0919			"Give the value for the back of the picture"
#define	TEXT0920			"Value for this standard area"
#define	TEXT0921			"too much object with size higher than autorized fragment"

	// choix des menus
#define	TEXT0930			"Handing"
#define	TEXT0931			"Half_Auto"
#define	TEXT0932			"Auto"
#define	TEXT0933			"Labellisation Auto/Handing"
#define	TEXT0934			"Yes, there is a standard"
#define	TEXT0935			"No, only auto-radiographic pictures"
#define	TEXT0936			"I don't remember"
#define	TEXT0937			"Up"
#define	TEXT0938			"Down"
#define	TEXT0939			"Resolution of PGM picture(300) "

	//divers
#define	TEXT0950			"QUIT ?"
#define	TEXT0951			"Another pgm file ? "
#define	TEXT0952			"LOADING..."

/*-*/



#define	TEXT1000			"Which picture ?"
#define TEXT1010			"Browse"
#define	TEXT1020			"Open file"

#define TEXT1100			"All (*)|*"

#define TEXT1200			"General caracteristics"
#define TEXT1201			"States"
#define TEXT1202			"Apply"
#define TEXT1203			"Refresh"
#define TEXT1204			"File"
#define TEXT1205			"First image"
#define TEXT1206			"Step"
#define TEXT1207			"Number of images"
#define TEXT1208			"Number of states"
#define TEXT1209			"Error : too much parameters in automate"
#define TEXT1210			"Paravision"
#define TEXT1211			"Chg dir"
#define TEXT1212			"Directory"
#define TEXT1213			"Pictures / sequence"
#define TEXT1214			"fMRI's informations"
#define TEXT1215			"Empty picture"

#define TEXT1300            "Error : detection of XVisual"
#define TEXT1310            "Error : can't create %i colors " \
                            "(%i existing for a maximum of %i)"
#define TEXT1320            "Assert: colormap # %d doesn't exist " \
                            "(only %d)"
#define TEXT1330            "Which colormap?"
#define TEXT1340            "New colormap"
#define TEXT1350            "Assert: incorrect image location " \
                            "(index %d, %d images only)\n"
#define TEXT1360            "Which picture?"
#define TEXT1370            "Error: colormap curve %i unknown\n"

#define TEXT1380            "Positive"
#define TEXT1390            "Negative"
#define TEXT1400            "Symmetrical"
#define TEXT1410            "Dissymmetrical"
#define TEXT1420            "Display mode?"
#define TEXT1430            "Error: all colormaps are bind"
#define TEXT1440            "Error: undefined %s event\n"
#define TEXT1450            "Incompatible automate. Use the 'filtrer' script"
#define TEXT1460            "Error: %s not set\n"
#define TEXT1470            "Position ?"

#define TEXT1480			"Pictures"
#define TEXT1490			"Select all"
#define TEXT1500			"Deselect all"
#define TEXT1510			"With creation"
#define TEXT1520			"Replace"
#define TEXT1530			"Colormap to be replaced"
#define TEXT1540			"Choice of values"

#define TEXT1550			"Clear dialog box"
#define TEXT1560			"Error : stage colormap needed"
#define TEXT1570			"Color #"
#define TEXT1580			"Type : "
#define TEXT1590			"Real values"
#define TEXT1600			"Percentage"
#define TEXT1610			"Unknown"

#define TEXT1700            "OK"
#define TEXT1710            "Cancel"
#define TEXT1720            "Help"
#define TEXT1730            "Close"
#define TEXT1740            "Yes"
#define TEXT1750            "No"

#define TEXT1800            "IRMf"
#define TEXT1810            "Colormap"
#define TEXT1820            "Choose a file"
#define TEXT1830            "Choose a picture file"
#define TEXT1840            "Information"
#define TEXT1850            "File already exists"
#define TEXT1860            "Warning"
#define TEXT1870            "Result"
#define TEXT1880            "Error"
#define TEXT1890            "Fatal error"
#define TEXT1900            "About"

#define TEXT2000            "Fini ?"
#define TEXT2010            "Cutoff setup"
#define TEXT2020            "Cardio"

#define TEXT2100            "Superpose"

#define TEXT2200            "Automates execution"
#define TEXT2210            "Stations choice"
#define TEXT2220            "Automates choice"

#define TEXT2300            "Erreur: '%s' variable undefined"

#define TEXT2400            "ROI"
#define TEXT2410            "Masque"
#define TEXT2420            "Choose the picture"
#define TEXT2430            "Choose the mask"


/* Markov segmentation messages */
#define MASK_QUEST          "Choose"
#define FULL_IMAGE          "Full image"
#define WITHOUT_BG          "Thresholded image "
#define NBR_CLASS_QUEST     "Number of classes ?"
#define ERR_NBITER          "Error: Number of iterations <=0\n"
#define ERR_NBCLASSES       "Error: Number of classes <=0\n"
#define ALGORITHM           "Estimation algorithm ?"
#define QUEST_EM            "EM (quick)"
#define QUEST_ICE           "ICE (accurate)"
#define QUEST_SEM           "SEM"
#define INIT_MARKOV         "Initialisation ?"
#define TEXT_NO_INIT        "No initialisation"
#define TEXT_KMEAN          "K-mean"
#define TEXT_FUZZY_KMEAN    "Fuzzy K-mean"
#define ERR_MASK            "Error: image doesn't have a mask\n"



/* fMRI messages */
#define ERR_MEM_ALLOC		"Memory allocation error"
#define ERR_LOAD_MRI		"Error : cannot load the mri file"
#define ERR_SAVE_PARAD		"Error : cannot save paradigm"
#define ERR_NO_PARAD		"Error : no paradigm to save\n"
#define ERR_NOT_A_PARAD		"Error : this file is not a paradigm\n"
#define ERR_NOT_2D_PARAD	"Error : this file is not a 2D paradigm\n"
#define ERR_NOT_3D_PARAD	"Error : this file is not a 3D paradigm\n"
#define ERR_PARAD_VOID		"Error : no paradigm has been defined\n"
#define ERR_CANT_MAKE_PAR	"Error : cannot create the paradigm\n"
#define ERR_CANT_SAVE		"Error : cannot save in this repertory\n"
#define ERR_IMG_NOT_LOADED	"Error : pictures haven't been loaded\n"
#define ERR_N_STATUS		"Error : At least 2 status for fMRI\n"
#define ERR_NO_RUPTURES     "Error :  ruptures are not load\n"

#define WRN_NIMG_SUP_PARAD	"Warning : the number of images is greater than the number of status of the paradigm.\n"
#define WRN_PARAD_SUP_NIMG	"Warning : the number of status of the paradigm is greater than the number of images.\n"

#define MSG_IGN_PATHS		"Ignore images paths"
#define MSG_SAVE_PATHS		"Include images paths"
#define MSG_CHOICE			"Select your choice"

#define TXT_PARAD_VISU		"Paradigm visualisation"
#define TXT_REST			"REST"
#define TXT_ACTIV			"STATUS "
#define TXT_STAT1			"STATUS 1"
#define TXT_STAT2			"STATUS 2"
#define TXT_STAT_ALL		"All status"
#define TXT_IMG_MAP             "image of the  brain map"
#define TXT_IMG_DELAY           "image of the delay"

#define ASK_N_STATUS		"Enter the number of status :"
#define ASK_THRES_PROC		"Enter the threshold of processing. (Current value : %f)"

#define UNIX_CMD_QUEST      "Enter your command :"
#define CHDIR_CMD_QUEST     "Which directory ?"
#define PLACE_MESG      "Where ?"
#define	OKCANCEL_MESG   "Confirm"
#define ANYVALUE_MESG   "Get a value"

#define ABOUT_MESG	"\nMedimax 2.01      \
             \n Copyright (c) 1993-2000 ULP-IPB-LSIIT Strasbourg\n   \
\n  J.P. Armspach \
\n  Ph. Etter, C. Nikou, 0. Musse, F. Bouleau  \
\n  T. BERST\
\n  and all students..... \n  \
\n All rights reserved GITIM\
\n http://www-ipb.u-strasbg.fr/gitim"  


/* fin fMRI */

#endif

