import itertools
from deployement.scons.wrapitk import get_instantiations

Import("env")
env = env.Clone()

env.Glob("*.py")
env.Use("itk")
env.PythonModule("_parse", ["parse.i", "parse.cpp"])

types = ["%s %s"%x 
         for x in itertools.product(["signed", "unsigned"], ["short", "long"])]
types += ["float"]
dimensions = [2]
instantiations = get_instantiations("itk::Image", types, dimensions)
instantiations = [((class_, type, dimension), (class_, type, dimension+1)) 
                  for class_, type, dimension in instantiations]
classes_template_info = [ ("itk::AssembleTilesImageFilter", instantiations, "pointer") ]
env.WrapITKPythonModule("AssembleTilesImageFilter", classes_template_info)
