import itertools
from deployement.scons.wrapitk import (get_scalar_types, get_dimensions)
from deployement.scons.wrapitk.utils import Instantiation
from deployement.scons.itk import wrapitk_root

Import("env")
env = env.Clone()
env.Glob("*.py")

env.Use("openmp")

types = get_scalar_types(wrapitk_root())
dimensions = [3]
instantiations = [[Instantiation("itk::Image", *x)] 
                  for x in itertools.product(types, dimensions)]

classes_template_info = [
    ("itk::Plane", [["float"], ["double"]], None),
    ("itk::SymmetryPlaneCalculator", instantiations, "Pointer")
]
env.WrapITKPythonModule("SymmetryPlane", classes_template_info)