# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info
if version_info >= (3,0,0):
    new_instancemethod = lambda func, inst, cls: _itkHiddenMarkovChainFilterPython.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_itkHiddenMarkovChainFilterPython', [dirname(__file__)])
        except ImportError:
            import _itkHiddenMarkovChainFilterPython
            return _itkHiddenMarkovChainFilterPython
        if fp is not None:
            try:
                _mod = imp.load_module('_itkHiddenMarkovChainFilterPython', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _itkHiddenMarkovChainFilterPython = swig_import_helper()
    del swig_import_helper
else:
    import _itkHiddenMarkovChainFilterPython
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


import ITKCommonBasePython
import itkEventObjectsPython
import pyBasePython
import itkImagePython
import itkFixedArrayPython
import itkCovariantVectorPython
import vnl_vectorPython
import vcl_complexPython
import vnl_matrixPython
import itkVectorPython
import vnl_vector_refPython
import ITKRegionsPython
import itkSizePython
import itkIndexPython
import itkOffsetPython
import itkPointPython
import itkMatrixPython
import vnl_matrix_fixedPython
import itkRGBAPixelPython
import itkRGBPixelPython
import itkImageToImageFilterAPython
import itkImageSourcePython
import itkVectorImagePython
import itkVariableLengthVectorPython
def itkHiddenMarkovChainFilterIF3IF3_New():
  return itkHiddenMarkovChainFilterIF3IF3.New()

class itkHiddenMarkovChainFilterIF3IF3(itkImageToImageFilterAPython.itkImageToImageFilterIF3IF3):
    """Proxy of C++ itkHiddenMarkovChainFilterIF3IF3 class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def __New_orig__():
        """__New_orig__()"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3___New_orig__()

    __New_orig__ = staticmethod(__New_orig__)
    def GetNb_images(self):
        """GetNb_images(self) -> unsigned int"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetNb_images(self)

    def SetNb_images(self, *args):
        """SetNb_images(self, unsigned int _arg)"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetNb_images(self, *args)

    def GetAtlas_bool(self):
        """GetAtlas_bool(self) -> bool"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetAtlas_bool(self)

    def SetAtlas_bool(self, *args):
        """SetAtlas_bool(self, bool _arg)"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetAtlas_bool(self, *args)

    def GetNumber_iter(self):
        """GetNumber_iter(self) -> unsigned int"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetNumber_iter(self)

    def SetNumber_iter(self, *args):
        """SetNumber_iter(self, unsigned int _arg)"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetNumber_iter(self, *args)

    def GetNumber_classes(self):
        """GetNumber_classes(self) -> unsigned int"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetNumber_classes(self)

    def SetNumber_classes(self, *args):
        """SetNumber_classes(self, unsigned int _arg)"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetNumber_classes(self, *args)

    def GetCriterion_outliers(self):
        """GetCriterion_outliers(self) -> unsigned int"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetCriterion_outliers(self)

    def SetCriterion_outliers(self, *args):
        """SetCriterion_outliers(self, unsigned int _arg)"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetCriterion_outliers(self, *args)

    def GetCriterion_outliers_value(self):
        """GetCriterion_outliers_value(self) -> float"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetCriterion_outliers_value(self)

    def SetCriterion_outliers_value(self, *args):
        """SetCriterion_outliers_value(self, float _arg)"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetCriterion_outliers_value(self, *args)

    def GetTaille_cube(self):
        """GetTaille_cube(self) -> unsigned int"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetTaille_cube(self)

    def SetTaille_cube(self, *args):
        """SetTaille_cube(self, unsigned int _arg)"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetTaille_cube(self, *args)

    def GetOuputSegImage(self):
        """GetOuputSegImage(self) -> itkImageF3"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetOuputSegImage(self)

    def GetOuputOutliersImage(self):
        """GetOuputOutliersImage(self) -> itkImageF3"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetOuputOutliersImage(self)

    def GetInputImage(self, *args):
        """GetInputImage(self, unsigned int idx)"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetInputImage(self, *args)

    def SetInputImage(self, *args):
        """SetInputImage(self, unsigned int idx, itkImageF3 image)"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetInputImage(self, *args)

    __swig_destroy__ = _itkHiddenMarkovChainFilterPython.delete_itkHiddenMarkovChainFilterIF3IF3
    def cast(*args):
        """cast(itkLightObject obj) -> itkHiddenMarkovChainFilterIF3IF3"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_cast(*args)

    cast = staticmethod(cast)
    def GetPointer(self):
        """GetPointer(self) -> itkHiddenMarkovChainFilterIF3IF3"""
        return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetPointer(self)

    def New(*args, **kargs):
        """New() -> itkHiddenMarkovChainFilterIF3IF3
        
        Create a new object of the class itkHiddenMarkovChainFilterIF3IF3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.
        
        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.
        
        The named parameters are used by calling the method with the same name prefixed by 'Set'.
        
        Ex:
        
          itkHiddenMarkovChainFilterIF3IF3.New( reader, Threshold=10 ) 
        
        is (most of the time) equivalent to:
        
          obj = itkHiddenMarkovChainFilterIF3IF3.New()
          obj.SetInput( 0, reader.GetOutput() )
          obj.SetThreshold( 10 )
        """
        obj = itkHiddenMarkovChainFilterIF3IF3.__New_orig__()
        import itkTemplate
        itkTemplate.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)

itkHiddenMarkovChainFilterIF3IF3.GetNb_images = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetNb_images,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.SetNb_images = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetNb_images,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.GetAtlas_bool = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetAtlas_bool,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.SetAtlas_bool = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetAtlas_bool,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.GetNumber_iter = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetNumber_iter,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.SetNumber_iter = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetNumber_iter,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.GetNumber_classes = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetNumber_classes,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.SetNumber_classes = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetNumber_classes,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.GetCriterion_outliers = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetCriterion_outliers,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.SetCriterion_outliers = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetCriterion_outliers,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.GetCriterion_outliers_value = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetCriterion_outliers_value,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.SetCriterion_outliers_value = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetCriterion_outliers_value,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.GetTaille_cube = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetTaille_cube,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.SetTaille_cube = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetTaille_cube,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.GetOuputSegImage = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetOuputSegImage,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.GetOuputOutliersImage = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetOuputOutliersImage,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.GetInputImage = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetInputImage,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.SetInputImage = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_SetInputImage,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3.GetPointer = new_instancemethod(_itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_GetPointer,None,itkHiddenMarkovChainFilterIF3IF3)
itkHiddenMarkovChainFilterIF3IF3_swigregister = _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_swigregister
itkHiddenMarkovChainFilterIF3IF3_swigregister(itkHiddenMarkovChainFilterIF3IF3)

def itkHiddenMarkovChainFilterIF3IF3___New_orig__():
  """itkHiddenMarkovChainFilterIF3IF3___New_orig__()"""
  return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3___New_orig__()

def itkHiddenMarkovChainFilterIF3IF3_cast(*args):
  """itkHiddenMarkovChainFilterIF3IF3_cast(itkLightObject obj) -> itkHiddenMarkovChainFilterIF3IF3"""
  return _itkHiddenMarkovChainFilterPython.itkHiddenMarkovChainFilterIF3IF3_cast(*args)



